[package]
name = "postman-tui"
version = "0.1.0"
edition = "2021"
authors = ["Yash <yashpc09@gmail.com>"]
description = "A simple API client (postman like) in your terminal"
license = "MIT OR Apache-2.0"
repository = "https://github.com/skyash-dev/postman-tui"
readme = "README.md"
keywords = ["postman", "tui", "ratatui", "http"]
categories = ["command-line-utilities", "network-programming"]


[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tui-input = "0.11.1"
